#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 4
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym_PLUS = 2,
  anon_sym_DASH = 3,
  anon_sym_SLASH = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_LT_EQ = 7,
  anon_sym_GT_EQ = 8,
  anon_sym_EQ_EQ = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_PIPE_PIPE = 11,
  anon_sym_AMP_AMP = 12,
  anon_sym_EQ = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  anon_sym_SEMI = 16,
  anon_sym_u8 = 17,
  anon_sym_u16 = 18,
  anon_sym_u32 = 19,
  anon_sym_u64 = 20,
  anon_sym_i8 = 21,
  anon_sym_i16 = 22,
  anon_sym_i32 = 23,
  anon_sym_i64 = 24,
  anon_sym_usize = 25,
  anon_sym_isize = 26,
  anon_sym_bool = 27,
  anon_sym_void = 28,
  anon_sym_LPAREN = 29,
  anon_sym_COMMA = 30,
  anon_sym_RPAREN = 31,
  anon_sym_LBRACE = 32,
  anon_sym_RBRACE = 33,
  anon_sym_return = 34,
  anon_sym_if = 35,
  anon_sym_else = 36,
  anon_sym_SLASH_SLASH = 37,
  aux_sym_comment_token1 = 38,
  anon_sym_struct = 39,
  anon_sym_DQUOTE = 40,
  aux_sym_string_literal_token1 = 41,
  sym_identifier = 42,
  sym_integer = 43,
  sym_source_file = 44,
  sym__definition = 45,
  sym__type = 46,
  sym_pointer_type = 47,
  sym__expression = 48,
  sym_binary_expression = 49,
  sym_bool = 50,
  sym__statement = 51,
  sym_primitive_type = 52,
  sym_variable_definition = 53,
  sym_function_definition = 54,
  sym_block = 55,
  sym_return_statement = 56,
  sym_if_statement = 57,
  sym_comment = 58,
  sym_struct_declaration = 59,
  sym_function_call = 60,
  sym_string_literal = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_function_definition_repeat1 = 63,
  aux_sym_block_repeat1 = 64,
  aux_sym_struct_declaration_repeat1 = 65,
  aux_sym_function_call_repeat1 = 66,
  alias_sym_function_call_name = 67,
  alias_sym_function_name = 68,
  alias_sym_function_parameter = 69,
  alias_sym_struct_field = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ] = "=",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_SEMI] = ";",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_usize] = "usize",
  [anon_sym_isize] = "isize",
  [anon_sym_bool] = "bool",
  [anon_sym_void] = "void",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_struct] = "struct",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__type] = "_type",
  [sym_pointer_type] = "pointer_type",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_bool] = "bool",
  [sym__statement] = "_statement",
  [sym_primitive_type] = "primitive_type",
  [sym_variable_definition] = "variable_definition",
  [sym_function_definition] = "function_definition",
  [sym_block] = "block",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_comment] = "comment",
  [sym_struct_declaration] = "struct_declaration",
  [sym_function_call] = "function_call",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_struct_declaration_repeat1] = "struct_declaration_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [alias_sym_function_call_name] = "function_call_name",
  [alias_sym_function_name] = "function_name",
  [alias_sym_function_parameter] = "function_parameter",
  [alias_sym_struct_field] = "struct_field",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_usize] = anon_sym_usize,
  [anon_sym_isize] = anon_sym_isize,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__type] = sym__type,
  [sym_pointer_type] = sym_pointer_type,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_bool] = sym_bool,
  [sym__statement] = sym__statement,
  [sym_primitive_type] = sym_primitive_type,
  [sym_variable_definition] = sym_variable_definition,
  [sym_function_definition] = sym_function_definition,
  [sym_block] = sym_block,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_comment] = sym_comment,
  [sym_struct_declaration] = sym_struct_declaration,
  [sym_function_call] = sym_function_call,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_struct_declaration_repeat1] = aux_sym_struct_declaration_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [alias_sym_function_call_name] = alias_sym_function_call_name,
  [alias_sym_function_name] = alias_sym_function_name,
  [alias_sym_function_parameter] = alias_sym_function_parameter,
  [alias_sym_struct_field] = alias_sym_struct_field,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_usize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_pointer_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_call_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_function_parameter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_struct_field] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_function_name,
  },
  [2] = {
    [1] = alias_sym_function_parameter,
  },
  [3] = {
    [1] = alias_sym_struct_field,
  },
  [4] = {
    [0] = alias_sym_function_call_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 3,
  [7] = 2,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 11,
  [18] = 18,
  [19] = 19,
  [20] = 13,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 37,
  [41] = 41,
  [42] = 39,
  [43] = 43,
  [44] = 44,
  [45] = 11,
  [46] = 19,
  [47] = 47,
  [48] = 24,
  [49] = 18,
  [50] = 16,
  [51] = 13,
  [52] = 22,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 68,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 89,
  [95] = 95,
  [96] = 91,
  [97] = 97,
  [98] = 93,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 15,
        '"', 83,
        '&', 4,
        '(', 70,
        ')', 72,
        '*', 37,
        '+', 38,
        ',', 71,
        '-', 39,
        '/', 41,
        ';', 53,
        '<', 42,
        '=', 50,
        '>', 43,
        'b', 106,
        'e', 100,
        'f', 88,
        'i', 86,
        'r', 96,
        's', 114,
        't', 107,
        'u', 87,
        'v', 105,
        '{', 73,
        '|', 33,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 15,
        '"', 83,
        '&', 4,
        '(', 70,
        ')', 72,
        '*', 37,
        '+', 38,
        ',', 71,
        '-', 39,
        '/', 40,
        ';', 53,
        '<', 42,
        '=', 50,
        '>', 43,
        'f', 88,
        't', 107,
        '{', 73,
        '|', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 83,
        '*', 37,
        '/', 6,
        'b', 106,
        'e', 100,
        'f', 88,
        'i', 86,
        'r', 96,
        's', 114,
        't', 107,
        'u', 87,
        'v', 105,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 83,
        '*', 37,
        '/', 6,
        'b', 106,
        'f', 88,
        'i', 86,
        'r', 96,
        's', 114,
        't', 107,
        'u', 87,
        'v', 105,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(49);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 7:
      if (lookahead == '1') ADVANCE(13);
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == '8') ADVANCE(58);
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(54);
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(60);
      END_STATE();
    case 10:
      if (lookahead == '2') ADVANCE(56);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == '4') ADVANCE(57);
      END_STATE();
    case 13:
      if (lookahead == '6') ADVANCE(59);
      END_STATE();
    case 14:
      if (lookahead == '6') ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(68);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 'z') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'z') ADVANCE(19);
      END_STATE();
    case 33:
      if (lookahead == '|') ADVANCE(48);
      END_STATE();
    case 34:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(85);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        ')', 72,
        '*', 37,
        ',', 71,
        '/', 6,
        'b', 26,
        'i', 7,
        's', 28,
        'u', 8,
        'v', 25,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(46);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_usize);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_usize);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_isize);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_isize);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_void);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_return);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_if);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_else);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(13);
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == '8') ADVANCE(58);
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == 's') ADVANCE(97);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(54);
      if (lookahead == 's') ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(102);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(118);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(90);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(119);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(98);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(117);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(103);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(115);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(91);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(109);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(89);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'z') ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'y')) ADVANCE(120);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'z') ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'y')) ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 35},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 35},
  [10] = {.lex_state = 35},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 35},
  [38] = {.lex_state = 35},
  [39] = {.lex_state = 35},
  [40] = {.lex_state = 35},
  [41] = {.lex_state = 35},
  [42] = {.lex_state = 35},
  [43] = {.lex_state = 35},
  [44] = {.lex_state = 35},
  [45] = {.lex_state = 35},
  [46] = {.lex_state = 35},
  [47] = {.lex_state = 35},
  [48] = {.lex_state = 35},
  [49] = {.lex_state = 35},
  [50] = {.lex_state = 35},
  [51] = {.lex_state = 35},
  [52] = {.lex_state = 35},
  [53] = {.lex_state = 35},
  [54] = {.lex_state = 35},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 35},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 35},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 79},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 5},
  [94] = {.lex_state = 79},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 34},
  [98] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_usize] = ACTIONS(1),
    [anon_sym_isize] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(92),
    [sym__definition] = STATE(10),
    [sym__type] = STATE(88),
    [sym_pointer_type] = STATE(88),
    [sym_primitive_type] = STATE(88),
    [sym_variable_definition] = STATE(10),
    [sym_function_definition] = STATE(10),
    [sym_comment] = STATE(10),
    [sym_struct_declaration] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(7),
    [anon_sym_isize] = ACTIONS(7),
    [anon_sym_bool] = ACTIONS(7),
    [anon_sym_void] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
  },
  [2] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(8),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(8),
    [sym_return_statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_struct_declaration] = STATE(8),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(8),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [3] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(2),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(2),
    [sym_return_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_struct_declaration] = STATE(2),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(2),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [4] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(8),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(8),
    [sym_return_statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_struct_declaration] = STATE(8),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(8),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [5] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(4),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(4),
    [sym_return_statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_comment] = STATE(4),
    [sym_struct_declaration] = STATE(4),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(4),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [6] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(7),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(7),
    [sym_return_statement] = STATE(7),
    [sym_if_statement] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_struct_declaration] = STATE(7),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(7),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [7] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(8),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(8),
    [sym_return_statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_struct_declaration] = STATE(8),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(8),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_u8] = ACTIONS(7),
    [anon_sym_u16] = ACTIONS(7),
    [anon_sym_u32] = ACTIONS(7),
    [anon_sym_u64] = ACTIONS(7),
    [anon_sym_i8] = ACTIONS(7),
    [anon_sym_i16] = ACTIONS(7),
    [anon_sym_i32] = ACTIONS(7),
    [anon_sym_i64] = ACTIONS(7),
    [anon_sym_usize] = ACTIONS(15),
    [anon_sym_isize] = ACTIONS(15),
    [anon_sym_bool] = ACTIONS(15),
    [anon_sym_void] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_return] = ACTIONS(19),
    [anon_sym_if] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [anon_sym_struct] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(31),
  },
  [8] = {
    [sym__type] = STATE(84),
    [sym_pointer_type] = STATE(84),
    [sym__expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_bool] = STATE(60),
    [sym__statement] = STATE(8),
    [sym_primitive_type] = STATE(84),
    [sym_variable_definition] = STATE(8),
    [sym_return_statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_comment] = STATE(8),
    [sym_struct_declaration] = STATE(8),
    [sym_function_call] = STATE(60),
    [sym_string_literal] = STATE(60),
    [aux_sym_block_repeat1] = STATE(8),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_true] = ACTIONS(46),
    [anon_sym_false] = ACTIONS(46),
    [anon_sym_u8] = ACTIONS(49),
    [anon_sym_u16] = ACTIONS(49),
    [anon_sym_u32] = ACTIONS(49),
    [anon_sym_u64] = ACTIONS(49),
    [anon_sym_i8] = ACTIONS(49),
    [anon_sym_i16] = ACTIONS(49),
    [anon_sym_i32] = ACTIONS(49),
    [anon_sym_i64] = ACTIONS(49),
    [anon_sym_usize] = ACTIONS(52),
    [anon_sym_isize] = ACTIONS(52),
    [anon_sym_bool] = ACTIONS(52),
    [anon_sym_void] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_return] = ACTIONS(57),
    [anon_sym_if] = ACTIONS(60),
    [anon_sym_SLASH_SLASH] = ACTIONS(63),
    [anon_sym_struct] = ACTIONS(66),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [sym_identifier] = ACTIONS(72),
    [sym_integer] = ACTIONS(75),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_STAR,
    ACTIONS(86), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(89), 1,
      anon_sym_struct,
    STATE(88), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    STATE(9), 6,
      sym__definition,
      sym_variable_definition,
      sym_function_definition,
      sym_comment,
      sym_struct_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(83), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [40] = 7,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(9), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_struct,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(88), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    STATE(9), 6,
      sym__definition,
      sym_variable_definition,
      sym_function_definition,
      sym_comment,
      sym_struct_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [80] = 2,
    ACTIONS(96), 11,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(94), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [109] = 3,
    ACTIONS(102), 1,
      anon_sym_else,
    ACTIONS(100), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(98), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [140] = 2,
    ACTIONS(106), 11,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(104), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [169] = 2,
    ACTIONS(110), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(108), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [197] = 2,
    ACTIONS(114), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(112), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [225] = 2,
    ACTIONS(118), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(116), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [253] = 2,
    ACTIONS(96), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(94), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [281] = 2,
    ACTIONS(122), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(120), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [309] = 2,
    ACTIONS(126), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(124), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [337] = 2,
    ACTIONS(106), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(104), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [365] = 2,
    ACTIONS(130), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(128), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [393] = 2,
    ACTIONS(134), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(132), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [421] = 3,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(136), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [451] = 2,
    ACTIONS(144), 10,
      anon_sym_true,
      anon_sym_false,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_return,
      anon_sym_if,
      anon_sym_struct,
      sym_identifier,
    ACTIONS(142), 13,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_DQUOTE,
      sym_integer,
  [479] = 2,
    ACTIONS(148), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(146), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [506] = 2,
    ACTIONS(152), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(150), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [533] = 2,
    ACTIONS(156), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [560] = 3,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(156), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 14,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [589] = 5,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(156), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 10,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [622] = 2,
    ACTIONS(166), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(164), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [649] = 2,
    ACTIONS(170), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(168), 16,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [676] = 10,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(156), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [719] = 7,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(156), 4,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 8,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [756] = 8,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(156), 4,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 7,
      anon_sym_PIPE_PIPE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [795] = 4,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(156), 6,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(154), 12,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      sym_integer,
  [826] = 11,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(182), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(186), 3,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_integer,
  [869] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      aux_sym_struct_declaration_repeat1,
    STATE(83), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [898] = 5,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      aux_sym_struct_declaration_repeat1,
    STATE(83), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(193), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [927] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_struct_declaration_repeat1,
    STATE(83), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [956] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      aux_sym_struct_declaration_repeat1,
    STATE(83), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [985] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_function_definition_repeat1,
    STATE(85), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [1014] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_struct_declaration_repeat1,
    STATE(83), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [1043] = 5,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_function_definition_repeat1,
    STATE(85), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(209), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [1072] = 5,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_function_definition_repeat1,
    STATE(85), 3,
      sym__type,
      sym_pointer_type,
      sym_primitive_type,
    ACTIONS(7), 12,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
  [1101] = 1,
    ACTIONS(94), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1120] = 1,
    ACTIONS(124), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1139] = 1,
    ACTIONS(216), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1158] = 1,
    ACTIONS(142), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1177] = 1,
    ACTIONS(120), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1196] = 1,
    ACTIONS(116), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1215] = 1,
    ACTIONS(104), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1234] = 1,
    ACTIONS(132), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1253] = 1,
    ACTIONS(218), 16,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_SLASH_SLASH,
      anon_sym_struct,
  [1272] = 2,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    ACTIONS(220), 14,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_RPAREN,
  [1292] = 10,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1328] = 1,
    ACTIONS(226), 14,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_RBRACE,
  [1345] = 9,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1378] = 9,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(230), 1,
      anon_sym_SEMI,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1411] = 9,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      anon_sym_SEMI,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1444] = 9,
    ACTIONS(176), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(178), 1,
      anon_sym_AMP_AMP,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    ACTIONS(158), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(160), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1477] = 1,
    ACTIONS(236), 14,
      anon_sym_STAR,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_bool,
      anon_sym_void,
      anon_sym_RPAREN,
  [1494] = 7,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      sym_identifier,
    ACTIONS(249), 1,
      sym_integer,
    STATE(62), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(238), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1521] = 7,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      sym_integer,
    STATE(62), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1548] = 7,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(254), 1,
      sym_integer,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1575] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(258), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1596] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(260), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1617] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(262), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1638] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1659] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(266), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1680] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(268), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1701] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(270), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(29), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1722] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(272), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1743] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(274), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1764] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(276), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1785] = 5,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(278), 1,
      sym_integer,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 5,
      sym__expression,
      sym_binary_expression,
      sym_bool,
      sym_function_call,
      sym_string_literal,
  [1806] = 2,
    ACTIONS(241), 3,
      anon_sym_RPAREN,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(280), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [1817] = 3,
    ACTIONS(282), 1,
      anon_sym_EQ,
    ACTIONS(284), 1,
      anon_sym_SEMI,
    ACTIONS(286), 1,
      anon_sym_LPAREN,
  [1827] = 3,
    ACTIONS(288), 1,
      anon_sym_SEMI,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block,
  [1837] = 3,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
    ACTIONS(292), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      sym_block,
  [1847] = 2,
    ACTIONS(294), 1,
      anon_sym_EQ,
    ACTIONS(296), 1,
      anon_sym_SEMI,
  [1854] = 1,
    ACTIONS(298), 2,
      anon_sym_STAR,
      sym_identifier,
  [1859] = 1,
    ACTIONS(300), 2,
      anon_sym_STAR,
      sym_identifier,
  [1864] = 2,
    ACTIONS(302), 1,
      anon_sym_STAR,
    ACTIONS(304), 1,
      sym_identifier,
  [1871] = 2,
    ACTIONS(302), 1,
      anon_sym_STAR,
    ACTIONS(306), 1,
      sym_identifier,
  [1878] = 2,
    ACTIONS(302), 1,
      anon_sym_STAR,
    ACTIONS(308), 1,
      sym_identifier,
  [1885] = 2,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
  [1892] = 1,
    ACTIONS(312), 2,
      anon_sym_STAR,
      sym_identifier,
  [1897] = 2,
    ACTIONS(302), 1,
      anon_sym_STAR,
    ACTIONS(314), 1,
      sym_identifier,
  [1904] = 1,
    ACTIONS(316), 1,
      aux_sym_comment_token1,
  [1908] = 1,
    ACTIONS(318), 1,
      anon_sym_DQUOTE,
  [1912] = 1,
    ACTIONS(320), 1,
      anon_sym_LBRACE,
  [1916] = 1,
    ACTIONS(322), 1,
      ts_builtin_sym_end,
  [1920] = 1,
    ACTIONS(324), 1,
      sym_identifier,
  [1924] = 1,
    ACTIONS(326), 1,
      aux_sym_comment_token1,
  [1928] = 1,
    ACTIONS(328), 1,
      anon_sym_SEMI,
  [1932] = 1,
    ACTIONS(330), 1,
      anon_sym_LBRACE,
  [1936] = 1,
    ACTIONS(332), 1,
      aux_sym_string_literal_token1,
  [1940] = 1,
    ACTIONS(334), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 40,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 109,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 169,
  [SMALL_STATE(15)] = 197,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 253,
  [SMALL_STATE(18)] = 281,
  [SMALL_STATE(19)] = 309,
  [SMALL_STATE(20)] = 337,
  [SMALL_STATE(21)] = 365,
  [SMALL_STATE(22)] = 393,
  [SMALL_STATE(23)] = 421,
  [SMALL_STATE(24)] = 451,
  [SMALL_STATE(25)] = 479,
  [SMALL_STATE(26)] = 506,
  [SMALL_STATE(27)] = 533,
  [SMALL_STATE(28)] = 560,
  [SMALL_STATE(29)] = 589,
  [SMALL_STATE(30)] = 622,
  [SMALL_STATE(31)] = 649,
  [SMALL_STATE(32)] = 676,
  [SMALL_STATE(33)] = 719,
  [SMALL_STATE(34)] = 756,
  [SMALL_STATE(35)] = 795,
  [SMALL_STATE(36)] = 826,
  [SMALL_STATE(37)] = 869,
  [SMALL_STATE(38)] = 898,
  [SMALL_STATE(39)] = 927,
  [SMALL_STATE(40)] = 956,
  [SMALL_STATE(41)] = 985,
  [SMALL_STATE(42)] = 1014,
  [SMALL_STATE(43)] = 1043,
  [SMALL_STATE(44)] = 1072,
  [SMALL_STATE(45)] = 1101,
  [SMALL_STATE(46)] = 1120,
  [SMALL_STATE(47)] = 1139,
  [SMALL_STATE(48)] = 1158,
  [SMALL_STATE(49)] = 1177,
  [SMALL_STATE(50)] = 1196,
  [SMALL_STATE(51)] = 1215,
  [SMALL_STATE(52)] = 1234,
  [SMALL_STATE(53)] = 1253,
  [SMALL_STATE(54)] = 1272,
  [SMALL_STATE(55)] = 1292,
  [SMALL_STATE(56)] = 1328,
  [SMALL_STATE(57)] = 1345,
  [SMALL_STATE(58)] = 1378,
  [SMALL_STATE(59)] = 1411,
  [SMALL_STATE(60)] = 1444,
  [SMALL_STATE(61)] = 1477,
  [SMALL_STATE(62)] = 1494,
  [SMALL_STATE(63)] = 1521,
  [SMALL_STATE(64)] = 1548,
  [SMALL_STATE(65)] = 1575,
  [SMALL_STATE(66)] = 1596,
  [SMALL_STATE(67)] = 1617,
  [SMALL_STATE(68)] = 1638,
  [SMALL_STATE(69)] = 1659,
  [SMALL_STATE(70)] = 1680,
  [SMALL_STATE(71)] = 1701,
  [SMALL_STATE(72)] = 1722,
  [SMALL_STATE(73)] = 1743,
  [SMALL_STATE(74)] = 1764,
  [SMALL_STATE(75)] = 1785,
  [SMALL_STATE(76)] = 1806,
  [SMALL_STATE(77)] = 1817,
  [SMALL_STATE(78)] = 1827,
  [SMALL_STATE(79)] = 1837,
  [SMALL_STATE(80)] = 1847,
  [SMALL_STATE(81)] = 1854,
  [SMALL_STATE(82)] = 1859,
  [SMALL_STATE(83)] = 1864,
  [SMALL_STATE(84)] = 1871,
  [SMALL_STATE(85)] = 1878,
  [SMALL_STATE(86)] = 1885,
  [SMALL_STATE(87)] = 1892,
  [SMALL_STATE(88)] = 1897,
  [SMALL_STATE(89)] = 1904,
  [SMALL_STATE(90)] = 1908,
  [SMALL_STATE(91)] = 1912,
  [SMALL_STATE(92)] = 1916,
  [SMALL_STATE(93)] = 1920,
  [SMALL_STATE(94)] = 1924,
  [SMALL_STATE(95)] = 1928,
  [SMALL_STATE(96)] = 1932,
  [SMALL_STATE(97)] = 1936,
  [SMALL_STATE(98)] = 1940,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_declaration, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_declaration, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_declaration, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_declaration, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 5, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 4),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 4),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 4),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_declaration_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_declaration_repeat1, 3, 0, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 3, 0, 2),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer_type, 1, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer_type, 2, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [322] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_meraki(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
